### ISSUE TITLE
gem can not be used as dependency

### ISSUE THREAD

**Issue by okliv** [feedbin/opml_saw#3]
if i try to add your gem as dependency for my gem using .gemspec file i receive

```
Could not find gem 'opml_saw (>= 0) ruby', which is required by gem 'opml_project_initializer (>= 0) ruby', in any of the sources
```

and it is not possible to pass :git or :path or anything else there :(

**Comment by benubois** [comment]
Hi @okliv,

Sorry for the install trouble! This has actually been removed from RubyGems so I'm afraid the only way to install it is through a Gemfile using the `github` or `git` integration.

If you'd like to fork it and submit it to RubyGems that would be fine.

Thanks!
